export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

. <(asdf completion bash)
. "$HOME/.cargo/env"
eval "$(fzf --bash)"
eval "$(starship init bash)"

alias poweroff="shutdown -h now"
alias reboot="shutdown -r now"
