background = 0xff1a1b26
base = 0xff24283b
alternate_base = 0xff414868
text = 0xffa9b1d6
bright_text = 0xffc0caf5
accent = 0xff0db9d7
accent_secondary = 0xffbb9af7

font_family = Hack Nerd Font
monospace_font_family = Hack Nerd Font Mono
